language: python
jdk: openjdk8
dist: trusty
root: false
cache:
  pip: true
python:
  - "3.6"
before_install:
  - mkdir -p /opt
  - wget -q http://archive.apache.org/dist/spark/spark-2.4.0/spark-2.4.0-bin-hadoop2.7.tgz
  - tar xzf spark-2.4.0-bin-hadoop2.7.tgz
  - rm spark-2.4.0-bin-hadoop2.7.tgz
  - pwd
  - export SPARK_HOME=/home/travis/build/vikassingh1000/pyspark_data_validation_utils/spark-2.4.0-bin-hadoop2.7
  - export PATH=$PATH:/home/travis/build/vikassingh1000/pyspark_data_validation_utils/spark-2.4.0-bin-hadoop2.7/bin
  - export PYTHONPATH="$(pwd)"
before_install:
  - pip3 install -U pip
install:
  - pip3 install -r requirements.txt
  - pip3 install -q findspark
  - pip3 install codecov
  - pip3 install --upgrade pip setuptools wheel
script:
  - python3 -m pytest
after_success:
  - python3 -m codecov
